name: Laravel Vue API Axios E-Commerce Application CI/CD

on:
  push:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.4"
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test

      # - name: Run Static Analysis
      #   run: vendor/bin/phpstan analyse -c phpstan.neon

      # - name: Run Style Check
      #   run: vendor/bin/phpcs --standard=PSR12 app/

      # - name: Run Code Formatter
      #   run: vendor/bin/php-cs-fixer fix --dry-run --diff

      # - name: Run Security Checker
      #   run: vendor/bin/security-checker security:check composer.lock

      # - name: Run Deprecation Checker
      # #   run: vendor/bin/deprecation-detector detect:run src/

      - name: Run Laravel Pint
        run: vendor/bin/pint --test

      # - name: Upload Code Coverage
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./storage/logs/coverage.xml
      #     fail_ci_if_error: true
      #     verbose: true
      #     flags: unittests
      #     name: codecov-umbrella-laravel-foor-ordering
  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            cd ${{ secrets.APP_PATH }} || { echo "Path not found: ${{ secrets.APP_PATH }}"; exit 1; }
            bash deploy.sh
            echo "Backend deployed successfully"
